// Originally generated by CMake

#ifndef SSPCPP_EXPORT_H
#define SSPCPP_EXPORT_H

#ifdef _WIN32

    #ifdef SSPCPP_STATIC_DEFINE
    #  define SSPCPP_EXPORT
    #  define SSPCPP_NO_EXPORT
    #else
    #  ifndef SSPCPP_EXPORT
    #    ifdef SSPCPP_EXPORTS
            /* We are building this library */
    #      define SSPCPP_EXPORT __declspec(dllexport)
    #    else
            /* We are using this library */
    #      define SSPCPP_EXPORT __declspec(dllimport)
    #    endif
    #  endif

    #  ifndef SSPCPP_NO_EXPORT
    #    define SSPCPP_NO_EXPORT 
    #  endif
    #endif

    #ifndef SSPCPP_DEPRECATED
    #  define SSPCPP_DEPRECATED __declspec(deprecated)
    #endif

    #ifndef SSPCPP_DEPRECATED_EXPORT
    #  define SSPCPP_DEPRECATED_EXPORT SSPCPP_EXPORT SSPCPP_DEPRECATED
    #endif

    #ifndef SSPCPP_DEPRECATED_NO_EXPORT
    #  define SSPCPP_DEPRECATED_NO_EXPORT SSPCPP_NO_EXPORT SSPCPP_DEPRECATED
    #endif

    #if 0 /* DEFINE_NO_DEPRECATED */
    #  ifndef SSPCPP_NO_DEPRECATED
    #    define SSPCPP_NO_DEPRECATED
    #  endif
    #endif
    
#else  // Likely Linux
    # define SSPCPP_EXPORT
#endif

#endif /* SSPCPP_EXPORT_H */
